### ISSUE TITLE
Update to axum 6

### ISSUE THREAD

**Issue by makorne** [omprakashsridharan/tower-casbin-auth#1]
Hi!
Thank you for great crate!

Please update to current axum version [from 5 to 6](https://github.com/tokio-rs/axum/releases?page=2)

**Comment by omprakashsridharan** [comment]
Thank you. Sure I will update and release in coming days

**Comment by omprakashsridharan** [comment]
I have updated the crate and released a new version 2.0.0 @makorne

**Comment by makorne** [comment]
Thank you!!!
 I will try it tomorrow!
